### ISSUE TITLE
검색기능 구현

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#118]
📌 Issue
- 만들어져있는 searchbar 에 검색기능을 구현하기

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|SearchBar|<img width="324" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/48238f80-537f-466c-919e-61634efc8617">

## 📝 To-do
- [x] 검색기능 구현
- [x] 각종 검색관련 디테일 구현

**Comment by ChangJin-Lee** [comment]
기대가 되는군요!
