### ISSUE TITLE
ItemDetailView QA

### ISSUE THREAD

**Issue by mollangcow** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#119]
📌 Issue

<!— 이슈에 대해 간략하게 설명해주세요 —> 
- ItemDetailView에서 품목명이 2줄을 초과할 때 좌측정렬되는 버그를 수정합니다.
- 또한 ItemDetailView와 관련된 일부 뷰를 수정합니다.
    - BasicListView 및 LongTermListView에서의 품목명 줄바꿈 수정.
    - TopAlertView 수정.
    - SmallButtonView 수정.
- ItemDetailView에서 스와이프하여 MainView 접근 기능을 추가합니다.

## 📸 ScreenShot
<!— 스크린샷을 넣고 기능에 대해 설명해주세요 ->
|기능|스크린샷|
|:--:|:--:|
|버그화면|<img width="233" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/123388563/865930db-471e-4681-b68a-5bddf372dc19">

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [ ] ItemDetailView 수정
- [ ] BasicList 및 LongTermListView 수정
- [ ] TopAlertView 수정
- [ ] SmallButtonView 수정
- [ ] 스와이프하여 뒤로가기 익스텐션 추가

**Comment by ChangJin-Lee** [comment]
쉬면서 해여 모카!!! 맥북 압수
