### ISSUE TITLE
HistoryView구현

### ISSUE THREAD

**Issue by mollangcow** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#12]
📌 Issue

- HistoryView구현

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|HistoryView|<img width="417" alt="스크린샷 2023-07-17 오후 2 55 38" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/123388563/af1bdd9a-0840-4b4b-9f80-493d7df4f009">
|SegmentedTab|<img width="417" alt="스크린샷 2023-07-17 오후 2 55 38 복사본" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/123388563/17e0d49f-6299-474f-9696-c932cd62598a">
|ItemList|<img width="417" alt="스크린샷 2023-07-17 오후 2 55 38 복사본 3" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/123388563/b5ff2e58-1cd1-468e-a0ec-9e874356cf1e">
|ItemListDateAndCount|<img width="417" alt="스크린샷 2023-07-17 오후 2 55 38 복사본 2" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/123388563/6031b5e6-46bd-42ec-9bda-d65865d7da70">
|ItemStatusEditButton|<img width="417" alt="스크린샷 2023-07-17 오후 2 55 38 복사본 4" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/123388563/0a9696e8-80b0-4d9f-92e9-96e42df845d1">

## 📝 To-do
- [x] HistoryView구현
- [x] SegmentedTab구현
- [x] ItemList구현
- [x] ItemListDateAndCount구현
- [x] ItemStatusEditButton구현

**Comment by ChangJin-Lee** [comment]
모카!!! 첫 이슈를 축하합니다! 유후!

**Comment by oxoamor** [comment]
모카 첫 이슈를 축하합니다 유후~~~!!!
