### ISSUE TITLE
ItemDetailView 기본 view 그리기

### ISSUE THREAD

**Issue by oxoamor** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#17]
📌 Issue

- MainView에서 식재료를 선택했을 때 나오는 ItemDetailView 뷰 그리기

## 📸 ScreenShot

|기능|스크린샷|
|:--:|:--:|
|ItemDetailView|![image](https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/97780163/df76c631-60ba-4e70-97e7-608d4726eb2a)
|(제목이 2줄일 때)|<img width="325" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/97780163/efb38a23-9fdf-4ad3-843e-e9557fae3b44">

## 📝 To-do

- [ ] 메인 페이지에서 식재료를 클릭했을 때 뜨는 상세 페이지 그리기

**Comment by ChangJin-Lee** [comment]
업무 완료~
