### ISSUE TITLE
TabBar Icon Change

### ISSUE THREAD

**Issue by mollangcow** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#51]
📌 Issue

- fixTabBarViewUI를 implementMainView로 merge했기 때문에 TabBar Icon의 교체 또한 implementMainView로 연결될 예정.
- 관련이슈
    - #48 

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|현재|<img width="800" alt="스크린샷 2023-07-25 오후 3 27 54" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/123388563/59ed4396-1cd4-485e-a7a1-b9009f446a30">
|교체 예정|<img width="850" alt="스크린샷 2023-07-25 오후 3 27 18" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/123388563/d4bcde64-9cd5-4458-93d5-e75861af7fd0">

## 📝 To-do
- [x] TabBar Icon 교체

**Comment by ChangJin-Lee** [comment]
교체 완료~
