### ISSUE TITLE
CoreData 모델 올리기

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#6]
📌 Issue
- 기본적인 CoreData Model 을 설계해서 올리기

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|CoreData 모델|<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/87b343ad-42a8-4f55-98bc-8c979ea6cf91">
|모델 내부 attribute 들|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/972c9dcf-a16b-49f5-b450-f904cea42901">
- CoreData 모델을 생성했고 그 안에 attribute 들도 세팅해서 올렸습니다

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [ ] CoreData Model 기본 세팅

**Comment by ChangJin-Lee** [comment]
# 생각해봄직한 사안
1. Entity를 두 개로 나눌지 하나의 큰 Entity로 만들까?
2. Attribute들 네이밍은 어떻게 지을까?

**Comment by alpaka99** [comment]
1. 우선 Entity 를 하나로 만들어 둔 후 테스트를 해서 더 필요하다면 Entity 하나를 더 만든다.
2. Attribute 네임은 추후 수정이 가능하니 일단은  제작함. 추후 수정 필요시 수정하겠음
