### ISSUE TITLE
Custom Camera 완성

### ISSUE THREAD

**Issue by wonniiii** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#7]
📌 Issue
-  커스텀한 카메라 완성하기

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|영수증 촬영|<img width="346" alt="스크린샷 2023-07-13 오후 5 23 33" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/81157265/92fbf879-0411-49f2-81f0-360cad7ad759">
|갤러리 |<img width="1164" alt="스크린샷 2023-07-13 오후 5 24 03" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/81157265/be38c052-1e09-4af8-b396-18c2d798a7de">

## 📝 To-do
- [x] Camera
- [x] CameraViewModel
- [x] CameraView

**Comment by ChangJin-Lee** [comment]
애니메이션 관련 탐구가 필요해 보이는군요! 
파이팅입니다.
